# ==========================
# MySQL Database
# ==========================

spring.datasource.url=jdbc:mysql://localhost:3306/fitzone
spring.datasource.username=root
spring.datasource.password=M@yur8760

# ==========================
# JPA / Hibernate
# ==========================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Optional (recommended)
spring.jpa.properties.hibernate.format_sql=true

# ==========================
# Error Handling
# ==========================

server.error.include-message=always
server.error.include-binding-errors=always

# Change this to NEVER in production
server.error.include-stacktrace=always

# ==========================
# Logging
# ==========================

logging.level.org.springframework.web=DEBUG